# Generated by Django 4.1.7 on 2023-03-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0017_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelleditem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cancelleditem',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='ordered',
        ),
        migrations.DeleteModel(
            name='Cancelled',
        ),
        migrations.DeleteModel(
            name='CancelledItem',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Ordered',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
