# Generated by Django 4.1.7 on 2023-03-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0019_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='ordered', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='active', max_length=7),
        ),
    ]
