# Generated by Django 4.1.7 on 2023-03-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0020_ordereditem_status_alter_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelleditem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cancelleditem',
            name='cancelled',
        ),
        migrations.DeleteModel(
            name='Cancelled',
        ),
        migrations.DeleteModel(
            name='CancelledItem',
        ),
    ]
